### PR TITLE
Full room data functionality to mirror Plug.DJ API used in most existing bots

### PR DESCRIPTION
**Pull request by backus**
Almost every function described on this page http://blog.plug.dj/api-documentation/ is included in this commit hold for a few non-essentials.  This addition should really accelerate the migration to server side nodeJS bots

### CODE REVIEW

**Comment by chrisinajar** [comment]
Nice!! Thanks a bunch, I'll look through this in a bit!

**Comment by TATDK** [comment]
Using this I got the following error

```
\node_modules\plugapi\src\room.coffee:144
      for (_i = 0, _len = djs.length; _i < _len; _i++) {
                             ^
TypeError: Cannot read property 'length' of undefined
    at Room.setDjs (\node_modules\plugapi\src\room.coffee:144:30)
    at Room.__bind (\node_modules\plugapi\src\room.coffee:3:61)
    at PlugAPI.messageHandler (\node_modules\plugapi\src\client.coffee:183:21)
    at PlugAPI.dataHandler (\node_modules\plugapi\src\client.coffee:125:16)
    at EventEmitter.__bind (\node_modules\plugapi\src\client.coffee:3:61)
    at EventEmitter.emit (events.js:126:20)
    at Object.XHRStreaming.emitData (\node_modules\plugapi\src\sockjs-client.js:323:30)
    at Object.XHRStreaming.running (\node_modules\plugapi\src\sockjs-client.js:294:26)
    at Object.StateMachine.invoke (\node_modules\plugapi\src\sockjs-client.js:359:29)
    at Object.StateMachine.stepper (\node_modules\plugapi\src\sockjs-client.js:388:29)
```

**Comment by chrisinajar** [comment]
Looks like "djs" isn't an array. Probably just needs a conditional before
an $.each or a for()...

**Comment by unusualbob** [comment]
That error just means that djs is undefined. I don't have the time to dive in, but maybe check typeof(djs) != 'undefined' before trying?

**Comment by backus** [comment]
I'll look into this should be easy to fix

**Comment by backus** [comment]
Ok I fixed the issue and I also added a super simple repl for people trying out the api to play around with.  Its as easy as

```
rescomp-12-248016:plugapi johnbackus$ node repl.js
[+] Joined dubstep-den
bot>bot.sendChat('hi')
```

**Comment by TATDK** [comment]
I can report that the same error still happens

**Comment by backus** [comment]
@TATDK I'm online now what room are you in I want to see whats causing it

**Comment by TATDK** [comment]
@backus I'm in friendshipismagic

**Comment by backus** [comment]
^ That commit is unrelated lol just some changes I was about to add when your message came in

**Comment by backus** [comment]
Alright there are definitely still some crashes involved with the additions but they aren't the same as the djs bug quoted earlier I'll dive into it soon to figure out whats going on

**Comment by chrisinajar** [comment]
This weekend I'll have the time to thoroughly test this and merge it in,
and I'll pop it into NPM as well.

Backus, drop your name and email how you want it to appear on the
contributors list at some point.

TATDK, thanks a ton for testing this for us!

**Comment by TATDK** [comment]
@chrisinajar I heard you were looking for me - I'm in the room now

Edit: you can contact me on TAT@plugpony.net if I'm not online the same time as you

**Comment by backus** [comment]
@chrisinajar my name is John Backus and email is johncbackus@gmail.com.  I also made an [npm profile](https://npmjs.org/~jbackus3) if that is helpful.

**Comment by chrisinajar** [comment]
Merging and I'll add some fixed and dry it out a bit

**Pull request merged**
